---
pipeline:
  cr:
    image: docker
    commands:
      - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD cr.chuhlomin.com
      - docker build -t cr.chuhlomin.com/do-deploy:latest .
      - docker push cr.chuhlomin.com/do-deploy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    secrets: [ docker_username, docker_password ]
    when:
      event: push
      branch: master
