---
kind: pipeline
type: docker
name: default

steps:
- name: cr
  image: plugins/docker
  settings:
    registry: cr.chuhlomin.com
    repo: cr.chuhlomin.com/docker-run
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
  when:
    event: push
    branch: master

trigger:
  branch:
  - master

image_pull_secrets:
  - dockerconfigjson
